# IMPORTANT: docker-compose.yaml uses .env file for its variables.

services:
  silkaraserver:
    image: ${DOCKER_REGISTRY-}silkaraserver
    container_name: silkaraserver
    build:
      context: .
      dockerfile: src/SilkaraServer/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    secrets:
      - db_user
      - db_password
    networks:
      - db_net
      - redis_net
    depends_on:
      - db
      - redis

    # Docker Compose just takes it and drops it inside the container so your C# code can read it.
    env_file:
      - .env.dev # or .env.prod
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=default
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis:
    image: redis:alpine
    container_name: silkara_redis
    networks:
      - redis_net
    # Using protected mode and ACL directly in the startup command
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --protected-mode yes
      --maxmemory 400mb
      --maxmemory-policy allkeys-lru
      --tcp-backlog 511
      --timeout 0
      --tcp-keepalive 300
    # Limiting container resources (DoS/memory leak protection)
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always

  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      # Setting neutral locale
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8"
    secrets:
      - db_user
      - db_password
      - db_cert
      - db_key
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - db_net
    command: >
      sh -c "cp /run/secrets/db_key /tmp/server.key && 
             chmod 600 /tmp/server.key && 
             chown postgres:postgres /tmp/server.key && 
             exec docker-entrypoint.sh postgres 
             -c ssl=on 
             -c ssl_cert_file=/run/secrets/db_cert 
             -c ssl_key_file=/tmp/server.key"

volumes:
  postgres_data:

networks:
  db_net:     # Only Silkara Server and Postgres can talk here
  redis_net:  # Only Silkara Server and Redis can talk here

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_cert:
    file: ./certs/server.crt
  db_key:
    file: ./certs/server.key
