<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\UTP\UTP.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Actions\ActionStrategies\" />
	</ItemGroup>

</Project>
